/**
 * PDF Generator - ShootSync
 * Generates shoot day briefing PDFs
 */

import { jsPDF } from 'jspdf'

interface ShootBriefingData {
  syndicateName: string
  shootDate: string
  locationName: string
  locationAddress?: string
  locationPostcode?: string
  locationWhat3Words?: string
  meetTime?: string
  drivesPlanned?: number
  expectedBag?: number
  captainNotes?: string
  guns: Array<{
    name: string
    pegNumber?: number
    isGuest?: boolean
  }>
  beaters: Array<{
    name: string
  }>
}

export function generateShootBriefingPDF(data: ShootBriefingData): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // Helper for centered text
  const centerText = (text: string, yPos: number, fontSize: number = 12) => {
    doc.setFontSize(fontSize)
    const textWidth = doc.getTextWidth(text)
    doc.text(text, (pageWidth - textWidth) / 2, yPos)
  }

  // Helper for section headers
  const sectionHeader = (text: string, yPos: number) => {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(text, 20, yPos)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    return yPos + 8
  }

  // Title
  doc.setFont('helvetica', 'bold')
  centerText('SHOOT BRIEFING', y, 20)
  y += 12

  // Syndicate name
  doc.setFont('helvetica', 'normal')
  centerText(data.syndicateName, y, 14)
  y += 15

  // Date box
  doc.setFillColor(240, 240, 240)
  doc.rect(20, y, pageWidth - 40, 12, 'F')
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  const dateText = `Date: ${data.shootDate}`
  doc.text(dateText, 25, y + 8)
  if (data.meetTime) {
    const meetText = `Meet: ${data.meetTime}`
    doc.text(meetText, pageWidth - 25 - doc.getTextWidth(meetText), y + 8)
  }
  y += 20

  // Location section
  y = sectionHeader('Location', y)
  doc.text(data.locationName, 20, y)
  y += 6
  if (data.locationAddress) {
    doc.setFontSize(10)
    doc.text(data.locationAddress, 20, y)
    y += 5
  }
  if (data.locationPostcode) {
    doc.text(`Postcode: ${data.locationPostcode}`, 20, y)
    y += 5
  }
  if (data.locationWhat3Words) {
    doc.text(`what3words: ${data.locationWhat3Words}`, 20, y)
    y += 5
  }
  y += 8

  // Shoot details
  if (data.drivesPlanned || data.expectedBag) {
    y = sectionHeader('Shoot Details', y)
    doc.setFontSize(11)
    if (data.drivesPlanned) {
      doc.text(`Drives planned: ${data.drivesPlanned}`, 20, y)
      y += 6
    }
    if (data.expectedBag) {
      doc.text(`Expected bag: ${data.expectedBag} birds`, 20, y)
      y += 6
    }
    y += 6
  }

  // Guns list
  if (data.guns.length > 0) {
    y = sectionHeader(`Guns (${data.guns.length})`, y)
    
    // Table header
    doc.setFillColor(34, 197, 94) // Green
    doc.rect(20, y - 4, pageWidth - 40, 8, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Peg', 25, y + 1)
    doc.text('Name', 50, y + 1)
    doc.text('Type', pageWidth - 50, y + 1)
    y += 8

    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'normal')

    data.guns.forEach((gun, index) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      
      // Alternating row colors
      if (index % 2 === 0) {
        doc.setFillColor(249, 250, 251)
        doc.rect(20, y - 4, pageWidth - 40, 7, 'F')
      }
      
      doc.text(gun.pegNumber?.toString() || '-', 25, y)
      doc.text(gun.name, 50, y)
      doc.text(gun.isGuest ? 'Guest' : 'Member', pageWidth - 50, y)
      y += 7
    })
    y += 8
  }

  // Beaters list
  if (data.beaters.length > 0) {
    y = sectionHeader(`Beaters (${data.beaters.length})`, y)
    
    const beaterNames = data.beaters.map(b => b.name).join(', ')
    const splitBeaters = doc.splitTextToSize(beaterNames, pageWidth - 40)
    doc.setFontSize(11)
    doc.text(splitBeaters, 20, y)
    y += splitBeaters.length * 6 + 8
  }

  // Captain's notes
  if (data.captainNotes) {
    if (y > 230) {
      doc.addPage()
      y = 20
    }
    y = sectionHeader("Captain's Notes", y)
    doc.setFontSize(10)
    const splitNotes = doc.splitTextToSize(data.captainNotes, pageWidth - 40)
    doc.text(splitNotes, 20, y)
    y += splitNotes.length * 5
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  centerText(`Generated by ShootSync on ${new Date().toLocaleDateString('en-GB')}`, footerY, 8)
  centerText('www.shootsync.co.uk', footerY + 4, 8)

  // Save the PDF
  const filename = `shoot-briefing-${data.shootDate.replace(/\s/g, '-')}.pdf`
  doc.save(filename)
}
